export const ACTIVITY_CARLIST_REDUCER_PENDING = "ACTIVITY_CARLIST_REDUCER_PENDING";
export const ACTIVITY_CARLIST_REDUCER_FULFILLED = "ACTIVITY_CARLIST_REDUCER_FULFILLED";
export const ACTIVITY_CARLIST_REDUCER_REJECT = "ACTIVITY_CARLIST_REDUCER_REJECT";
export const ACTIVITY_CARLIST_REDUCER_SEARCH = "ACTIVITY_CARLIST_REDUCER_SEARCH";
export const ACTIVITY_CARLIST_REDUCER_FULFILLED_SEARCH = "ACTIVITY_CARLIST_REDUCER_FULFILLED_SEARCH";
export const ACTIVITY_CARLIST_REDUCER_CLEARED_SEARCH = "ACTIVITY_CARLIST_REDUCER_CLEARED_SEARCH";

export const CAR_FILTER_PENDING = "CAR_FILTER_PENDING";
export const CAR_FILTER_FULFILLED = "CAR_FILTER_FULFILLED";
export const CAR_FILTER_REJECTED = "CAR_FILTER_REJECTED";
